MyPortfolyo/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyPortfolyo.DAL.Context;
using MyPortfolyo.DAL.Entities;

namespace MyPortfolyo.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
		

	}
}

MyPortfolyo/Controllers/MessageController.cs
using Microsoft.AspNetCore.Mvc;
using MyPortfolyo.DAL.Context;
using MyPortfolyo.DAL.Entities;

namespace MyPortfolyo.Controllers
{
	public class MessageController : Controller
	{
		MyPortfolioContext _context=new MyPortfolioContext();
		public IActionResult Inbox()
		{
			var values = _context.Messages.ToList();

			return View(values);
		}
		public IActionResult ChangeReadToTrue(int Id)
		{
			var value=_context.Messages.Find(Id);
			value.İsRead = true;	
			_context.SaveChangesAsync();
			return RedirectToAction("Inbox");
		}
		public IActionResult ChangeReadToFalse(int Id)
		{
			var value = _context.Messages.Find(Id);
			value.İsRead = false;
			_context.SaveChangesAsync();
			return RedirectToAction("Inbox");
		}

		public ActionResult DeleteMessage(int Id)
		{
			var value = _context.Messages.Find(Id);
			_context.Messages.Remove(value);	
			_context.SaveChangesAsync();
			return RedirectToAction("Inbox");
		}

		public ActionResult MessageDetail(int Id)
		{
			var value = _context.Messages.Find(Id);
	       return View(value);
		}

		//[HttpPost]
		//public async Task<IActionResult> SendMessage(Message message)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		message.SendDate = DateTime.Now;
		//		message.İsRead = false;
		//		_context.Messages.Add(message);
		//		await _context.SaveChangesAsync();
		//		return RedirectToAction("Index", "Default");
		//	}
		//	return View("Error");
		//}



	}
}

MyPortfolyo/Views/Shared/Components/_ContactComponentPartial/Default.cshtml
@model List<MyPortfolyo.DAL.Entities.Message>

<section id="contact" class="s-contact target-section">

    <div class="overlay"></div>

    <div class="row narrow section-intro">
        <div class="col-full">
            <h3>İletişim</h3>
            <h1>Bana Yazın </h1>

            <p class="lead">Lorem ipsum Dolor adipisicing nostrud et aute Excepteur amet commodo ea dolore irure esse Duis nulla sint fugiat cillum ullamco proident aliquip quis qui voluptate dolore veniam Ut laborum non est in officia.</p>
        </div>
    </div>

    <div class="row contact__main">
        <div class="col-eight tab-full contact__form">
            <form name="contactForm" id="contactForm" method="post" asp-controller="Message" asp-action="SendMessage">
                <fieldset>
                    <div class="form-field">
                        <input name="NameSurname" type="text" id="NameSurname" placeholder="Name" minlength="2" required class="full-width">
                    </div>
                    <div class="form-field">
                        <input name="Email" type="email" id="Email" placeholder="Email" required class="full-width">
                    </div>
                    <div class="form-field">
                        <input name="Subject" type="text" id="Subject" placeholder="Subject" class="full-width">
                    </div>
                    <div class="form-field">
                        <textarea name="MessageDetail" id="MessageDetail" placeholder="message" rows="5" required class="full-width"></textarea>
                    </div>
                    <div class="form-field">
                        <button type="submit" class="full-width btn--primary">Submit</button>
                    </div>
                </fieldset>
            </form>



            <!-- contact-warning -->
            <div class="message-warning">
                Something went wrong. Please try again.
            </div>

            <!-- contact-success -->
            <div class="message-success">
                Your message was sent, thank you!<br>
            </div>

        </div>
        <div class="col-four tab-full contact__infos">
            <h4 class="h06">Telefon</h4>
            <p>
                Phone: (+90) 555 125 12<br>
               
            </p>

            <h4 class="h06">Email</h4>
            <p>
                someone@holawebsite.com<br>
                
            </p>

            <h4 class="h06">Adres</h4>
            <p>
                1600 Amphitheatre Parkway<br>
                Mountain View, CA<br>
                94043 US
            </p>
        </div>

    </div>

</section>